Repository ballerina-platform/ballerina-www, pull requests merged in 2018-04, with the labels that each got.

#665 Fix minor doc issue
  website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md
Labels: Content/Bug Fix

#660 Add a service description to the quick tour guide
  website/two-column-pages/docs/learn/quick-tour.md
Labels: Content/Improvement

#664 Add a description to the endpoint construct within quick start guide
  website/two-column-pages/docs/learn/quick-tour.md
Labels: Content/Improvement

#661 Add connector description to quick start guide
  website/two-column-pages/docs/learn/quick-tour.md
Labels: Content/Improvement

#667 Add a description to composer segment within quick tour
  website/two-column-pages/docs/learn/quick-tour.md
Labels: Content/Improvement

#679 Create how-to-document-ballerina-code.md
  website/two-column-pages/docs/learn/how-to-document-ballerina-code.md
Labels: Content/New

#678 Update observability doc
  website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md
Labels: Content/Improvement

#700 Add articles.
  website/two-column-pages/docs/learn.md
Labels: Content/Addition

#676 Update license-of-site.md
  website/two-column-pages/docs/license-of-site.md
Labels: Content/Addition

#703 Update learn.md
  website/two-column-pages/docs/learn.md
Labels: Content/Improvement
