Repository ballerina-platform/ballerina-www, pull requests merged in 2018-06, with the labels that each got.

#857 Adding star and watch actions to for GitHub repo
  website/two-column-pages/docs/learn/quick-tour.md
  website/two-column-pages/docs/open-source.md
Labels: Content/Addition

#872 [Getting Started] Content update: "Installing on Windows" section
  website/two-column-pages/docs/learn/getting-started.md
Labels: Content/Bug Fix, Type/Docs

#908 Fix syntax changes related time scale property
  website/two-column-pages/docs/learn/ballerina-streaming-reference.md
Labels: Content/Improvement
